# Generated by Django 4.1.3 on 2023-01-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creada',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datecompleted',
            new_name='realizada',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='titulo',
        ),
    ]
