# Generated by Django 4.1.3 on 2023-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_created_task_creada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='importante',
        ),
        migrations.AddField(
            model_name='task',
            name='completada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
